---
- name: Backup show version and other user level commands
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Show an save version ./output
      ios_command:
        commands:
          - show version

      register: print_output

    -  debug: var=print_output.stdout_lines

    - name: save output to a file
      copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"
