---
- name: Manage GNS3 devices
  hosts: 172.16.1.104
  gather_facts: false
  connection: network_cli

  tasks:
    - name: enable ospf
      ios_config:
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
      become: yes
      become_method: enable

      register: print_output

    -  debug: var=print_output
